### ISSUE TITLE
How do I use this software?

### ISSUE THREAD

**Issue by woutersamaey** [velbus/python-velbustcp#1]
How do I use this software?
Do I need a PC that is permanently connected to Velbus using the USB connection?

**Comment by MDAR** [comment]
You would need some kind of machine running 24/7 that is connected to a Velbus USB interface and your local computer network, it could be anything that is capable of running Python, if you want access 24/7.


The same applies to the Ubuntu Snap solution.

**Comment by dukeofphilberg** [comment]
Hi @woutersamaey, sorry for the late response.

What @MDAR is saying is correct, all you'd need is a PC and USB interface running Python. 

If you're not looking to run your own solution, the VMBSIG is a module that directly connects to your bus with a network interface.
