### ISSUE TITLE
Please add a license?

### ISSUE THREAD

**Issue by nagisa** [velbus/python-velbustcp#12]
Please document the license under terms of which this software is made available to use, and possibly package and redistribute. The absence of one at the very least prevents making this available in package managers.

Thank you!

**Comment by dukeofphilberg** [comment]
Hi there,

We'll look to add a license soon. We already have this packaged as a snap: https://snapcraft.io/velbus-tcp

**Comment by dukeofphilberg** [comment]
Addressed in #16
